spring:
  datasource:
    url: jdbc:mariadb://localhost/test01
    username: root
    password: green502

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml